spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flytansuo?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: rootpwd
  flyway:
    baseline-on-migrate: true
    sql-migration-prefix: SQLVERSION
server:
  port: 8090